export { TitleSlide } from './TitleSlide'
export { WhoAmISlide } from './WhoAmISlide'
export { ConferencesSlide } from './ConferencesSlide'
export { WhatToExpectSlide } from './WhatToExpectSlide'
export { RegistrationSlide } from './RegistrationSlide'
export { ParticipantsSlide } from './ParticipantsSlide'
export { ThanksSlide } from './ThanksSlide'
