// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";

const prismaConfigDir = path.dirname(fileURLToPath(import.meta.url));
// `npx prisma` runs with cwd=api; default dotenv only loads api/.env (often missing).
dotenv.config({ path: path.resolve(prismaConfigDir, "../.env") });
dotenv.config({ path: path.resolve(prismaConfigDir, ".env") });

function getDatabaseUrl(): string {
  const user = process.env.POSTGRES_USER;
  const password = process.env.POSTGRES_PASSWORD;
  const host = process.env.POSTGRES_HOST;
  const port = process.env.POSTGRES_PORT;
  const db = process.env.POSTGRES_DB;
  return `postgresql://${user}:${encodeURIComponent(password!)}@${host}:${port}/${db}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
